const adjectives = [
    'big',
    'bland',
    'clumpy',
    'deep',
    'great',
    'grim',
    'hasty',
    'little',
    'nice',
    'old',
    'sad',
    'slippery',
    'small',
    'strong',
    'tiny',
    'vile',
    'wet',
    /* added from Rachel's list */
    'gentle',
    'lone',
    'pale',
    'sweet',
];
const comparatives = [
    'greater',
    'inner',
    'lesser',
    'outer',
];
const colors = [
    'amber',
    'blue',
    'cyan',
    'green',
    'mauve',
    'orange',
    'puce',
    'purple',
    'red',
    'teal',
    'violet',
    'yellow',
];

const animals = [
    'bear',
    'beaver',
    'bird',
    'buffalo',
    'dog',
    'elk',
    'fox',
    'goose',
    'hedgehog',
    'monkey',
    'owl',
    'pony',
    'possum',
    'turkey',
    'weasel',
    'worm',
];
const naturalFeatures = [
    'bay',
    'bayou',
    'beach',
    'bluff',
    'creek',
    'ditch',
    'forest',
    'gap',
    'grove',
    'hill',
    'meadow',
    'mountain',
    'plain',
    'prairie',
    'point',
    'rapids',
    'river',
    'rock',
    'springs',
    'sunrise',
    'sunset',
    'swamp',
    'tree',
    'valley',
    'woods',
];
const trees = [
    'aspen',
    'birch',
    'cedar',
    'cherry',
    'cypress',
    'elm',
    'larch',
    'maple',
    'oak',
    'pine',
    'poplar',
    'spruce',
    'walnut',
];
const vegetables = [
    'bean',
    'beet',
    'broccoli',
    'cabbage',
    'carrot',
    'cauliflower',
    'corn',
    'cucumber',
    'eggplant',
    'garlic',
    'leek',
    'lettuce',
    'onion',
    'parsnip',
    'pea',
    'potato',
    'pumpkin',
    'radish',
    'squash',
    'tomato', // Yes, yes it's technically a berry but come on
    'turnip',
    'yam',
    'zucchini',
];
const fruits = [
    'apple',
    'banana',
    'blueberry',
    'cranberry',
    'gooseberry',
    'grape',
    'grapefruit',
    'guava',
    'kiwi',
    'lemon',
    'lime',
    'orange',
    'peach',
    'pineapple',
    'pomegranate',
    'raspberry',
    'strawberry',
    'watermelon',
];
const foods = [
    'biscuit',
    'burger',
    'cheese',
    'egg',
    'ham',
    'honey',
    'pickle',
].concat(vegetables, fruits);
const nouns = [
    'Accent',
    'Accident',
    'Afterthought',
    'Appliance',
    'Basin',
    'Bath',
    'Bird',
    'Birthday',
    'Blanket',
    'Bleach',
    'Bludgeon',
    'Boat',
    'Bongo',
    'Bucket',
    'Building',
    'Candle',
    'Caption',
    'Chandelier',
    'Chardonnay',
    'Compliance',
    'Crayon',
    'Cushion',
    'Divorce',
    'Dripp',
    'Expedition',
    'Feather',
    'Festival',
    'Flesh',
    'Friendship',
    'Gargle',
    'Government',
    'Gradient',
    'Hammock',
    'Heritage',
    'Hickory',
    'Jellyfish',
    'Lamp',
    'Lampshade',
    'Lighthouse',
    'Loaf',
    'Lumber',
    'Lump',
    'Opposite',
    'Passion',
    'Pepper',
    'Pleasant',
    'Prose',
    'Quicksand',
    'Rainstorm',
    'Sand',
    'Scissor',
    'Shape',
    'Sidetable',
    'Snakes',
    'Sofa',
    'Squeak',
    'Stink',
    'Surprise',
    'Taste',
    'Toothpaste',
    'Trains',
    'Trousers',
    'Vest',
    'Volcano',
    'Worm',
    'Weasel',
    /* nouns added from Rachel's list */
    'Autumn',
    'Berry',
    'Bird',
    'Day',
    'Dragon',
    'Dream',
    'Evening',
    'Free',
    'Frost',
    'Humble',
    'Leather',
    'Meadow',
    'Moon',
    'Morning',
    'Night',
    'Ocean',
    'Rain',
    'Salt',
    'Shadow',
    'Spark',
    'Spider',
    'Spring',
    'Sugar',
    'Summer',
    'Velvet',
    'Winter',
    'Witch',
    'Wonder',
];

// Industries
const industries = [
    'Accommodation',
    'Agriculture',
    'Apparel',
    'Appliance',
    'Art',
    'Beverage',
    'Big Data',
    'Broadcasting',
    'Commodities',
    'Computer',
    'Construction',
    'Credit',
    'Data Processing',
    'Education',
    'Electronics',
    'Entertainment',
    'Film',
    'Finance',
    'Fishing',
    'Food',
    'Forestry',
    'Furniture',
    'Gambling',
    'Health',
    'Historical Sites',
    'Information Services',
    'Insurance',
    'Internet',
    'Laundry',
    'Logging',
    'Machinery',
    'Maintenance',
    'Management',
    'Manufacturing',
    'Mining',
    'Money',
    'Motion Picture',
    'Motor Vehicle',
    'Museums',
    'Nursing',
    'Oil and Gas',
    'Performing Arts',
    'Petrochemical',
    'Plastics',
    'Printing',
    'Publishing',
    'Real Estate',
    'Recreation',
    'Religion',
    'Rental and Leasing',
    'Retail',
    'Robotics',
    'Science',
    'Securities',
    'Sightseeing',
    'Social Media',
    'Sound Recording',
    'Sporting Goods',
    'Telecommunications',
    'Textile',
    'Theme Parks',
    'Transit',
    'Transportation',
    'Waste Management',
    'Water',
];

export {adjectives, animals, colors, comparatives, industries, naturalFeatures, nouns, trees, fruits, vegetables, foods};
